# Generated by Django 3.2.24 on 2024-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Processing', 'PROCESSING'), ('Completed', 'COMPLETED'), ('Canceled', 'CANCELED')], default='Pending', max_length=20),
        ),
    ]
